const assert=require('node:assert/strict');
const {bestBuySoldOut}=require('./bestbuy.js');
const {productRule,resolveBestBuyRule}=require('./profiles.js');
const url='https://www.bestbuy.com/product/console/TEST/sku/6691841';
const rule={store:'Best Buy',productId:'6691841'};
let visible=true,buttonLabel='Close',disabled=false,clicks=0,heading='Sold out';
let text='Sold out Sorry, this item was not added to your cart because it’s no longer available.';
const shown={getClientRects:()=>[{}]};
const close={...shown,get innerText(){return buttonLabel},matches:()=>disabled,getAttribute:()=>null,click:()=>{clicks++;visible=false;}};
const title={...shown,get innerText(){return heading}};
const modal={getClientRects:()=>visible?[{}]:[],get innerText(){return text},querySelector:s=>s.includes('primary-button-6691841')?close:s.includes('header-6691841')?title:null};
const error={...shown,innerText:'This item is currently unavailable for online purchase. The item was not added to your cart.'};
global.location={href:url,hostname:'www.bestbuy.com'};
global.getComputedStyle=()=>({visibility:'visible'});
global.document={querySelector:s=>s.includes('container-6691841')?modal:s==='[data-testid="limit-error-alert"]'?error:null};
let identifiers=['pdp-coming-soon-6691841','pdp-gated-purchase-failure-modal-container-6691841'];
document.querySelectorAll=()=>identifiers.map(id=>({...shown,getAttribute:()=>id}));
const canonical=productRule('https://www.bestbuy.com/product/console/J7GSL57HTY');
assert.equal(canonical.needsSku,true);assert.equal(resolveBestBuyRule(canonical).productId,'6691841');
identifiers.push('pdp-pre-order-6691853');assert.equal(resolveBestBuyRule(canonical).needsSku,true,'conflicting product identifiers are rejected');
identifiers=[];assert.equal(resolveBestBuyRule(canonical).needsSku,true,'missing SKU waits');
assert.equal(bestBuySoldOut(rule,url).modal,true);assert.equal(clicks,0,'read-only probe does not close');
assert.equal(bestBuySoldOut(rule,url,true).unavailable,true);assert.equal(clicks,1);
assert.equal(bestBuySoldOut(rule,url).modal,false,'close is verified against the DOM');
assert.equal(bestBuySoldOut(rule,url).unavailable,true,'remaining inline rejection is recognized');
visible=true;heading="You're in line";assert.equal(bestBuySoldOut(rule,url,true).unavailable,false);assert.equal(clicks,1);
heading='Sold out';text='This item may be available later';assert.equal(bestBuySoldOut(rule,url,true).unavailable,false);
text='Sorry, this item was not added to your cart because it’s no longer available.';
buttonLabel='Place order';assert.ok(bestBuySoldOut(rule,url,true).error);assert.equal(clicks,1);
buttonLabel='Close';disabled=true;assert.ok(bestBuySoldOut(rule,url,true).error);assert.equal(clicks,1);
assert.equal(bestBuySoldOut({...rule,productId:'OTHER'},url,true).unavailable,false);
global.location.href='https://www.bestbuy.com/cart';assert.equal(bestBuySoldOut(rule,url,true).unavailable,false);assert.equal(clicks,1);
for(const k of ['location','getComputedStyle','document'])delete global[k];
console.log('PASS: exact Best Buy sold-out modal, unique Close control, inline rejection, incomplete messages, queue and navigation guards');
