const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const {ensureFulfillment}=require('./profiles.js');
let selected=false,clicked=0,disabled=false,unavailable=false;
const button={getClientRects:()=>[{}],matches:()=>disabled,innerText:'',get checked(){return selected},getAttribute:n=>n==='aria-label'?`Pickup ${unavailable?'Not available':'Ready on Release Date'}`:null,click:()=>{clicked++;selected=true;}};
global.document={querySelectorAll:s=>s.includes('role="radio"')?[button]:[],getElementById:()=>null};
global.getComputedStyle=()=>({visibility:'visible'});
assert.equal(ensureFulfillment({store:'Best Buy'},'pickup',false).ready,false);
assert.equal(clicked,0);
assert.equal(ensureFulfillment({store:'Best Buy'},'pickup',true).changed,true);
assert.equal(clicked,1);
assert.equal(ensureFulfillment({store:'Best Buy'},'pickup',false).ready,true);
assert.equal(clicked,1);
unavailable=true;assert.equal(ensureFulfillment({store:'Best Buy'},'pickup',true).ready,false);assert.equal(clicked,1);
selected=false;button.id='fulfillment-Shipping';button.getClientRects=()=>[];
button.getAttribute=n=>n==='aria-label'?'Shipping Arrives Nov 5 Free':null;
global.document.querySelectorAll=s=>s==='input#fulfillment-Shipping'?[button]:[];
global.document.querySelector=s=>s==='label[for="fulfillment-Shipping"]'?{click:()=>{clicked++;selected=true;}}:null;
assert.equal(ensureFulfillment({store:'Walmart'},'shipping',true).changed,true);
assert.equal(ensureFulfillment({store:'Walmart'},'shipping',false).ready,true);
const ship={getClientRects:()=>[{}],matches:()=>false,innerText:'Ship to Home 2-3 business days',getAttribute:()=>null};
global.document.querySelectorAll=s=>s==='button'?[ship]:s==='h6'?[{getClientRects:()=>[{}],innerText:'Delivery: Ship to Home'}]:[];
assert.equal(ensureFulfillment({store:'GameStop'},'shipping',false).ready,true);
assert.equal(ensureFulfillment({store:'GameStop'},'pickup',true).ready,false);
assert.equal(ensureFulfillment({store:'Nintendo'},'pickup',true).ready,false);
assert.equal(ensureFulfillment({store:'Nintendo'},'shipping',true).ready,true);
delete global.document;delete global.getComputedStyle;
let timer,delay,sent;
const fakeNow=100000;
const context=vm.createContext({location:{href:'https://store.example/product'},Date:{now:()=>fakeNow},clearTimeout:()=>{},setTimeout:(fn,ms)=>{timer=fn;delay=ms;return 1},chrome:{runtime:{sendMessage:async m=>{sent=m}}}});
vm.runInContext(fs.readFileSync(__dirname+'/page-timers.js','utf8'),context);
vm.runInContext("armPageTimer('https://store.example/product',105000)",context);
assert.equal(delay,5000);timer();assert.equal(sent.type,'refreshDue');assert.equal(sent.deadline,105000);
sent=undefined;context.location.href='https://store.example/cart';timer();assert.equal(sent,undefined);
console.log('PASS: saved Best Buy pickup, hidden Walmart shipping radio, GameStop shipping, unavailable modes, five-second timer, navigation guard');
